import com.tanghao.bigdata.drools.domain.request.MobilePaymentRequest;
import com.tanghao.bigdata.drools.domain.response.RuleResponse;
import com.tanghao.bigdata.drools.enums.EnumRuleResponseLevel;
import com.tanghao.bigdata.drools.service.PhoneNoBlacklistService;

rule "pay_rule"
no-loop true
	when
        $pay : MobilePaymentRequest(RuleResponse.checkIsNull(response) && amount > 50);
    then
        $pay.setResponse("9999",EnumRuleResponseLevel.LOW.getCode(),"金额单笔金额超50了");
		update($pay);
end

rule "pay_rule2"
no-loop true
	when
        $pay : MobilePaymentRequest(RuleResponse.checkIsNull(response) && PhoneNoBlacklistService.isBlack(mobile));
    then
        $pay.setResponse("9999",EnumRuleResponseLevel.LOW.getCode(),"手机号在黑名单中");
		update($pay);
end

rule "pay_rule3"
no-loop true
	when
        $pay : MobilePaymentRequest(RuleResponse.checkIsNull(response) && amount > 31);
    then
        $pay.setResponse("9999",EnumRuleResponseLevel.LOW.getCode(),"金额单笔金额超31了");
		update($pay);
        System.out.println("hello, 支付金额超31啦");
end
