package com.canthny.drools_kie_demo.domain;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Assets implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private java.lang.Long money;
    private java.lang.Long stock;
    private java.lang.Long fund;

    public Assets() {
    }

    public java.lang.Long getMoney() {
        return this.money;
    }

    public void setMoney(java.lang.Long money) {
        this.money = money;
    }

    public java.lang.Long getStock() {
        return this.stock;
    }

    public void setStock(java.lang.Long stock) {
        this.stock = stock;
    }

    public java.lang.Long getFund() {
        return this.fund;
    }

    public void setFund(java.lang.Long fund) {
        this.fund = fund;
    }

    public Assets(java.lang.Long money, java.lang.Long stock,
                  java.lang.Long fund) {
        this.money = money;
        this.stock = stock;
        this.fund = fund;
    }

}