package com.canthny.drools_kie_demo.domain;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class UserInfo implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private java.lang.Long id;
    private java.lang.String name;
    private java.lang.Integer age;
    private java.lang.String accountNo;

    private java.lang.String risk_type;

    private com.canthny.drools_kie_demo.domain.Assets assets;

    public UserInfo() {
    }

    public java.lang.Long getId() {
        return this.id;
    }

    public void setId(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.String getName() {
        return this.name;
    }

    public void setName(java.lang.String name) {
        this.name = name;
    }

    public java.lang.Integer getAge() {
        return this.age;
    }

    public void setAge(java.lang.Integer age) {
        this.age = age;
    }

    public java.lang.String getAccountNo() {
        return this.accountNo;
    }

    public void setAccountNo(java.lang.String accountNo) {
        this.accountNo = accountNo;
    }

    public java.lang.String getRisk_type() {
        return this.risk_type;
    }

    public void setRisk_type(java.lang.String risk_type) {
        this.risk_type = risk_type;
    }

    public com.canthny.drools_kie_demo.domain.Assets getAssets() {
        return this.assets;
    }

    public void setAssets(com.canthny.drools_kie_demo.domain.Assets assets) {
        this.assets = assets;
    }

    public UserInfo(java.lang.Long id, java.lang.String name,
                    java.lang.Integer age, java.lang.String accountNo,
                    java.lang.String risk_type,
                    com.canthny.drools_kie_demo.domain.Assets assets) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.accountNo = accountNo;
        this.risk_type = risk_type;
        this.assets = assets;
    }

}